### ISSUE TITLE
Old-auth request stanza is sent on sasl-authenticated connection

### ISSUE THREAD

**Issue by isbear** [mcabber/loudmouth#1]
Commit b94583bb7db80803c48add517a5559d45b6f3a58 causes loudmouth to send old authentication request, if server has not provided sasl auth methods - and that is the case, when connection is already previously authenticated with sasl. Ejabberd in this case just ignores request (still, reply handler will hang around until connection object is destroyed), but prosody sends error reply, that causes connection to go back into 'open' state.

**Comment by wschlich** [comment]
Is this still valid for 1.5.2?

**Comment by isbear** [comment]
Commit in question was rolled back in commit b5a9de5b2bb78da5d3f57d3a0e8b08d2fc3746de, so the issues should be resolved.
