### ISSUE TITLE
Please do proper releases and not just snapshot tarballs.

### ISSUE THREAD

**Issue by darix** [mcabber/loudmouth#13]
Hi,

as the original upstream repository seems dead it might be worth to start releasing from your repository.
Talking to the old upstream probably a good idea. But given the library still sees use by projects (including yours), I think it would be a good idea to have proper releases again.

Thoughts?

**Comment by tyll** [comment]
yes, regular releases would be nicer for distributions.
@mhallendal - could you maybe redirect people from your repo to this to make this the new upstream?

**Comment by mhallendal** [comment]
@tyll sure, I went ahead and made my fork a fork off this one instead and added a comment in the description.

**Comment by McKael** [comment]
OK, thank you @mhallendal - we'll try to publish a new "official" release then.
Thanks to @darix & @tyll as well!

**Comment by McKael** [comment]
I have tagged release 1.5.1 and the archive/tarball is available at https://mcabber.com/files/loudmouth/.
Let me know if there is any issue with it!

**Comment by bfontaine** [comment]
Thank you @McKael; [Homebrew](http://brew.sh/) now uses the 1.5.1 version.

**Comment by McKael** [comment]
Done.
Release is there <https://mcabber.com/files/loudmouth/>, with announcements on [mcabber.com](https://mcabber.com) and the [jdev](http://mail.jabber.org/pipermail/jdev/2015-November/090136.html) mailing list.

Thank you all!

**Comment by mhallendal** [comment]
@McKael awesome, that's great!
