### ISSUE TITLE
gtk-doc has been broken in loudmouth 1.5.2

### ISSUE THREAD

**Issue by Fale** [mcabber/loudmouth#24]
Due to the fact that loudmouth-1.5.1 shipped with a (not-empty) file gtk-doc.make while loudmouth-1.5.2 ships an empty gtk-doc.make file

**Comment by wschlich** [comment]
?

**Comment by Fale** [comment]
Downloading the tar from https://mcabber.com/files/loudmouth/ and un-tar-ing them, is possible to notice that version 1.5.1 and 1.5.2 have big changes that seems to be way bigger than those present in git. I'm not sure why is this, but it is.
One of the files that really changed is the gtk-doc.make file that was full in version 1.5.1 and is empty in version 1.5.2

**Comment by McKael** [comment]
Indeed, the 1.5.2 has extra directories (autom4te.cache, as well as some .deps/.libs that shouldn't be there) -- my mistake.

I think I'll release a proper 1.5.3 with the changes franky has committed.

**Comment by darix** [comment]
can we help with the release?

**Comment by McKael** [comment]
Sorry for the delay, should be fixed now, with the 1.5.3 release.
