### ISSUE TITLE
Manually deactivate libidn during build

### ISSUE THREAD

**Issue by MikePetullo** [mcabber/loudmouth#27]
The loudmouth build process seems to rely entirely on pkg-tool to decide if it should build against libidn. This appears to cause problems with build systems such as the one for OpenWrt. In this case, the libidn package exists, but we do not want loudmouth to build against it unless the user specifies its use.

Would it be possible to modify loudmouth so that it supports an explicit --disable-idn flag? This might behave in a manner similar to the checks for OpenSSL.

Please see also https://github.com/openwrt/packages/issues/4187.

**Comment by MikePetullo** [comment]
Pull request: https://github.com/mcabber/loudmouth/pull/28

**Comment by McKael** [comment]
Merged, thanks for the patch!
