### ISSUE TITLE
Loudmouth 1.5.3 does not compile

### ISSUE THREAD

**Issue by MikePetullo** [mcabber/loudmouth#32]
GCC 7.3.0 fails with the following when trying to compile loudmouth 1.5.3:

lm-sasl.c: In function 'sasl_md5_prepare_response':
lm-sasl.c:532:32: error: comparison between pointer and zero character constant [-Werror=pointer-compare]
     if (nonce == NULL || nonce == '\0') {
                                ^~
lm-sasl.c:532:26: note: did you mean to dereference the pointer?
     if (nonce == NULL || nonce == '\0') {

It seems that the second expression should be "*nonce == '\0'".

**Comment by McKael** [comment]
Hi Michael,

This is actually already fixed in the repository (duplicate with #30).
Feel free to reopen if I'm mistaken!

We should probably make a release with this fix included...

Mikael
